name: Build Portable Binaries

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        default: '1.0.0'
      description:
        description: 'Release description'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - target: arm64
            os: android64
            pkg_target: node16-linux-arm64
            triple: aarch64-linux-android
          - target: arm
            os: android32
            pkg_target: node16-linux-armv7
            triple: armv7a-linux-androideabi

    steps:
    - uses: actions/checkout@v4
    
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d-%H%M%S')" >> "$GITHUB_OUTPUT"
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
        add-to-path: false

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          python3 \
          cmake

    - name: Install dependencies
      run: |
        # Install project dependencies
        npm install
        
        # Install pkg locally
        npm install --save-dev pkg
        
        # Show pkg version and targets
        npx pkg --version
        npx pkg --targets

    - name: Create pkg config
      run: |
        node -e "
          const fs = require('fs');
          const pkg = require('./package.json');
          
          pkg.bin = 'src/index.js';
          pkg.pkg = {
            assets: [
              'src/**/*',
              'config/**/*',
              'node_modules/**/*'
            ],
            targets: [ '${{ matrix.pkg_target }}' ]
          };
          
          fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
        "

    - name: Build Binary
      run: |
        echo "Building for target: ${{ matrix.pkg_target }}"
        npx pkg . \
          --target ${{ matrix.pkg_target }} \
          --output telegram-file-server-${{ matrix.os }} \
          --public \
          --debug
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: telegram-file-server-${{ matrix.os }}*
        tag_name: v${{ inputs.version }}-${{ matrix.os }}-${{ steps.date.outputs.date }}
        name: Telegram File Server ${{ matrix.os }} v${{ inputs.version }}
        body: |
          Version: ${{ inputs.version }}
          Platform: ${{ matrix.os }}
          Architecture: ${{ matrix.arch }}
          Build Date: ${{ steps.date.outputs.date }}
          
          ${{ inputs.description }}
          
          ### Notes
          - This build is compiled for Linux ${{ matrix.target }}
          - Requires root access on Android
          - Minimum Android API level: 21
          - Built with NDK r25c
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: telegram-file-server-${{ matrix.os }}
        path: telegram-file-server-${{ matrix.os }}*
        compression-level: 0
