name: Build Portable Binaries

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - target: linux-x64
            os: linux
          - target: win-x64
            os: windows
          - target: linux-arm64
            os: android

    steps:
    - uses: actions/checkout@v4
    
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d-%H%M%S')" >> "$GITHUB_OUTPUT"
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 16
    
    - name: Install dependencies
      run: |
        npm ci
        npm install -g nexe
    
    - name: Build binary
      run: |
        nexe src/index.js -o telegram-file-server-${{ matrix.os }} --target ${{ matrix.target }}
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: telegram-file-server-${{ matrix.os }}*
        tag_name: v${{ github.run_number }}-${{ matrix.os }}-${{ steps.date.outputs.date }}
        name: Telegram File Server ${{ matrix.os }} - ${{ steps.date.outputs.date }}
        body: Portable binary for ${{ matrix.os }} architecture
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: telegram-file-server-${{ matrix.os }}
        path: telegram-file-server-${{ matrix.os }}*
        compression-level: 0
