name: Build Portable Binaries

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        default: '1.0.0'
      description:
        description: 'Release description'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - target: android-arm64
            os: android64
            pkg_target: node16-android-arm64
            arch: arm64-v8a
          - target: android-arm
            os: android32
            pkg_target: node16-android-arm
            arch: armeabi-v7a

    steps:
    - uses: actions/checkout@v4
    
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d-%H%M%S')" >> "$GITHUB_OUTPUT"
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
        add-to-path: false

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          python3 \
          cmake

    - name: Setup Android environment
      run: |
        export ANDROID_NDK_HOME="${ANDROID_NDK_LATEST_HOME}"
        echo "ANDROID_NDK_HOME=${ANDROID_NDK_HOME}" >> $GITHUB_ENV
        echo "${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        # First install telegram dependencies
        npm install --ignore-scripts
        
        # Install nan and other build tools
        npm install --save-dev \
          nan \
          node-gyp \
          @mapbox/node-pre-gyp \
          pkg

    - name: Configure node-gyp for Android
      run: |
        export TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
        export TARGET=${{ matrix.target == 'android-arm64' && 'aarch64' || 'armv7a' }}-linux-androideabi
        export API=21
        
        # Set Android specific compiler flags
        export AR=$TOOLCHAIN/bin/llvm-ar
        export CC=$TOOLCHAIN/bin/$TARGET$API-clang
        export CXX=$TOOLCHAIN/bin/$TARGET$API-clang++
        export LINK=$TOOLCHAIN/bin/$TARGET$API-clang++
        export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
        export STRIP=$TOOLCHAIN/bin/llvm-strip
        
        # Build native modules
        npm rebuild --target_arch=${{ matrix.target == 'android-arm64' && 'arm64' || 'arm' }} --target_platform=android

    - name: Create pkg config
      run: |
        node -e "
          const fs = require('fs');
          const pkg = require('./package.json');
          
          pkg.bin = 'src/index.js';
          pkg.pkg = {
            assets: [
              'src/**/*',
              'config/**/*',
              'node_modules/**/*',
              'build/Release/**/*'
            ],
            targets: [ '${{ matrix.pkg_target }}' ]
          };
          
          fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
        "

    - name: Build Binary
      run: |
        npx pkg . \
          --target ${{ matrix.pkg_target }} \
          --output telegram-file-server-${{ matrix.os }} \
          --public
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: telegram-file-server-${{ matrix.os }}*
        tag_name: v${{ inputs.version }}-${{ matrix.os }}-${{ steps.date.outputs.date }}
        name: Telegram File Server ${{ matrix.os }} v${{ inputs.version }}
        body: |
          Version: ${{ inputs.version }}
          Platform: ${{ matrix.os }}
          Architecture: ${{ matrix.arch }}
          Build Date: ${{ steps.date.outputs.date }}
          
          ${{ inputs.description }}
          
          ### Notes
          - This build requires root access on Android
          - Tested on Android API level 21 and above
          - Built with NDK r25c
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: telegram-file-server-${{ matrix.os }}
        path: telegram-file-server-${{ matrix.os }}*
        compression-level: 0
